namespace: production
kongDatabase:
  name: kong-database
  port: 5432
  image: postgres:9.6
  user: kong
  password: kongpass
  dbName: kong

kong:
  name: kong

plugins:
  protoc: /root/k8s-install/protobuf/protoc

influxdb:
  user: test
  password: testPassword123
  org: test
  initBucket: init_bucket
  initAuthToken: test
serviceCenter:
  cpuLimit: 10m