# 拉取代码仓库的ssh公钥
apiVersion: v1
kind: ConfigMap
metadata:
  name: key
data:
  {{- (.Files.Glob "key/*").AsConfig | nindent 2 }}
---
# 初始化应用使用的脚本
apiVersion: v1
kind: ConfigMap
metadata:
  name: shell
data:
  {{- (.Files.Glob "shell/*").AsConfig | nindent 2 }}
---
# 应用运行使用的通用配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  {{- (.Files.Glob "config/*").AsConfig | nindent 2 }}