apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: config
          configMap:
            name: config
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        - name: nginx
          image: moyusir233/graduation-design:frontend
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: config
          ports:
            - containerPort: 80
          livenessProbe:
            periodSeconds: 60
            httpGet:
              port: 80
              path: /options
          readinessProbe:
            periodSeconds: 20
            httpGet:
              port: 80
              path: /options
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx
