apiVersion: batch/v1
kind: Job
metadata:
  name: test-datacollection
  namespace: test
spec:
  template:
    metadata:
      name: build
      labels:
        app: build
    spec:
      volumes:
        - name: key
          configMap:
            name: key
            # ssh密钥权限必须为0600
            defaultMode: 0600
        - name: shell
          configMap:
            name: init-shell
            defaultMode: 0777
            items:
              - key: init.sh
                path: init.sh
      containers:
        - name: build
          image: golang:1.16
          imagePullPolicy: IfNotPresent
          command: ["/init.sh"]
#          command:
#            - /bin/bash
#            - -c
#            - sleep 3600
          env:
            - name: PROJECT_REPO_ADDRESS
              value: "git@gitee.com:moyusir/util.git"
            - name: PROJECT_DIR
              value: "util"
            - name: TEST_PREFIX
              value: "Test"
            - name: USERNAME
              value: "test"
            - name: DEVICE_CLASS_COUNT
              value: "5"
            - name: SERVICE_NAME
              value: "test"
            - name: SERVICE_HOST
              value: "nginx.test.svc.cluster.local"
            - name: APP_DOMAIN_NAME
              value: "kong.test.svc.cluster.local"
          volumeMounts:
            - mountPath: /root/.ssh
              name: key
            - mountPath: /init.sh
              name: shell
              subPath: init.sh
      restartPolicy: Never

