server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
data:
  redis:
    host: network-manage-redis.production.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
  influxdb:
    serverUrl: http://influxdb.production.svc.cluster.local:8086
    authToken: test
    org: test
    taskOffset: 0s
  deviceStateRegisterInfo: /etc/app-configs/register_info.json
