logLevel: INFO
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 300s
    port: 8000
  grpc:
    addr: 0.0.0.0:9000
    timeout: 300s
    maxIdleTime: 300s
data:
  redis:
    host: network-manage-redis.production.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 10
    minIdleConns: 5
  influxdb:
    serverUrl: http://influxdb.production.svc.cluster.local:8086
    authToken: test
    org: test
