server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
  gateway:
    address: http://kong.production.svc.cluster.local:8001
  cluster:
    namespace: production
  compilationCenter:
    address: compilation-center.production.svc.cluster.local:9000
  appDomainName: gd-k8s-master01
  influxdb:
    serverUrl: http://influxdb.production.svc.cluster.local:8086
    authToken: test
    org: test
data:
  redis:
    host: network-manage-redis.production.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2
